### ISSUE TITLE
mask() function is somewhat ill defined

### ISSUE THREAD

**Issue by ReblochonMasque** [pirsquared/Str2D#2]
I found the `mask()` function difficult to understand, and here is an attempt at clarifying it:

**1 - rename it `apply_mask()`**

**2- what does it do?**
```  [A]
input  --------------------------------------------------->   "the truth is out there"
mask   --------------------------------------------------->   " --- ----- -- --- ----"

     apply_mask(inp=inp, mask=mask)  --------------------->   "t---t-----i--o---t----"
```
which is the standard vanilla expected result, the mask acts like a filter where only characters marked with the special masking char (white space) go through; the rest is replaced by the characters of the mask.

However, when trying to use the `invert` flag argument, the result is not what I expected:
```
     apply_mask(inp=inp, mask=mask, invert=True))  ------->   " he  ruth  s  ut  here"
```
which, in my opinion should give the opposite (the 'negative') of the previous result, but does not: the blocked characters are replaced by a white space:)
This is more what I expected:  
```
     expectation was  ------------------------------------>   "-he -ruth -s -ut -here"
```
with dashes '-' replacing the masked elements, and characters from the original string going through. This can be obtained by 'inverting' the mask, and calling `apply_mask()` with the same arguments as in `[A]`:
``` [B]
input  --------------------------------------------------->   "the truth is out there"
inverted_mask   ------------------------------------------>   "-   -     -  -   -    "

     apply_mask(inp=inp, mask=inverted_mask)  ------------>   "-he -ruth -s -ut -here"
```

suggestions:
-------------
These are general suggestions to improve the definition and implementation of `apply_mask()`, they are not limited to the inconsistency described above.

1 - use a caret `^` instead of a white space as a marker for the 'go through' positions in a mask, and use a dash '-' for the blocked places: _[this is edited, I changed my mind from a previous suggestion; I found that explicit markers were more readable than white space]_
```
      used at present                    suggested change
"the truth is out there"           "the truth is out there"
" --- ----- -- --- ----"           "^ --^-----^--^---^----"
```

2 - I think that the flag `invert`, when set to `true`, should transform the mask in a fashion similar to what photographic negatives do: the masked elements become unmasked, and vice versa. This would look like that using the same example as above.
```
      used at present                    suggested change
"-   -     -  -   -    "           "-^^^-^^^^^-^^-^^^-^^^^"
```

3 - Choosing a dash `-` or a star `*` as default replacement character for blocked elements is probably a better, more intuitive choice, than a white space.

4 - In my opinion, and for simplicity, I believe that optional replacement characters should not be part to the mask, but that an additional optional string of replacement text should be provided in addition to `inp` and `mask`.
At this moment, I find the option of using the mask characters to replace chars from the original input very confusing.

5 - It is likely that a function or a group of functions `make_mask` will be useful.
---> `make_mask(pattern)`
---> `make_mask_from(a list of indices)`
---> `make_mask_from(string, list_of_chars_to_mask)`

6 - `invert_mask(mask)`, returning the 'negative' of the `mask` provided should be extracted.

[edit]:
7 - upon starting coding a prototype, it became immediately obvious that **`mask` should be a class (`Mask`)**.

 I wish we could discuss this, and maybe clarify further some of the use cases. Then, I am willing to rewrite the function(s) and send a pull request.

**Comment by pirsquared** [comment]
New year has occupied my time. We can set up a room on SO, as you mentioned, and discuss further. I’m inclined to agree with your observations. Thanks for taking an interest. We’ll talk soon.

**Comment by pirsquared** [comment]
As per our SO discussion: I really like this concept.  I'd like to see a robust mask class developed and then we can generalize it to 2D and discuss how we apply it to a Str2D object.  I suspect this will be really useful in 1D in its own right.

**Comment by ReblochonMasque** [comment]
this can be closed

**Comment by ReblochonMasque** [comment]
Hello Sean, Happy New year.

I was wondering if you were still working on this package.

Cheers
Fred

**Comment by pirsquared** [comment]
I've rebooted this project and have incorporated my interpretation of this feature.  Each Str2D instance is a wrapper around a 2D numpy structured array where the first field is a character array of single dtype 'U1' indicating a single character.  The second field is an int8 array of zeros and ones indicating a binary opacity.  The field is named 'alpha' to mirror a png field.
